spring:
  application:
    name: gkart-user-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    log-resolved-exception: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gKartDb
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 9000
  servlet:
    context-path: "/gkart/user-service"
  ssl:
    key-alias: gkart
    key-store-password: passw0rd
    key-store: classpath:gkartKeyStore.jks
    enabled: true

jwt:
  secret: ${jwt_secret}